### ISSUE TITLE
OGSpy 3.3.7 et problème de remontée de flotte

### ISSUE THREAD

**Issue by Roms0406** [OGSteam/mod-flottes#3]
Bonjour, bonsoir,

Suite à la mise à jour vers OGSpy 3.3.7  et les xtenses en adéquation, la page flotte n'est plus fonctionnelle avec ce mod.
Probablement en concordance avec les nouveaux vaisseaux mais à vérifier ;)

**Comment by WAT02110** [comment]
hi, 
je confirme:
 Erreur critique mysql - Req : UPDATE ogspy_mod_flottes SET `CLE`=5287, `CLO`=1543, `CR`=667, `VB`=90, `TRA`=119, `BMD`=79, `DST`=96, `EDLM`=5, `FAU`=92, `ECL`=375, `PT`=1944, `GT`=125, `VC`=4, `REC`=747, `SE`=4102, `planet_name`='Lune', `coordinates`='4:406:8', `date`=1613516400 WHERE user_id=5 AND planet_id=201 - Erreur n°1054 **Unknown column 'FAU' in 'field list'**
 
 peut on corriger ceci en ajoutant ce champ à la table?
 
 thx!

**Comment by pitch314** [comment]
C'est bon ce problème avait été corrigé dans une mise à jour prenant en compte la V7.

La version courante du mod 1.1.4 la prend en compte.

(PS : c'est peut-être le même souci vu que autoupdate ne peux plus se connecter à Github =>install manuel)

**Comment by WAT02110** [comment]
Je suis en 1.1.4 :)

**Comment by pitch314** [comment]
FAU et ECL ont été ajoutés dans la version 1.2.0, l'erreur SQL ne devrait pas arriver.

Si tu as accès à la BDD, quelles sont les colonnes de la table ogspy_mod_flottes ?

**Comment by WAT02110** [comment]
le lien vers la release "latest" renvoie vers la 1.1.4.
j'ai pris la branche master en 1.2.1 et j'ai une table correct. mais l'affichage est vide + ne contient pas les colonnes de ces vaisseaux

**Comment by pitch314** [comment]
Que le champ soit vide après la migration cela est normal.

Le reste vide si on importe des données ?

**Comment by WAT02110** [comment]
ogspy_mod_flottes est vide. pas de message d'erreur dans les logs:
21/02/2021 13:29:22 : [Xtense][GM-FF V2.9.6] wat02110 envoie la flotte de sa planète SOAD (4:372:7)

je n'ai aucun logs sql via ogspy
mais la table est vide.

si besoin je suis sur le discord pour echanger

**Comment by pitch314** [comment]
=>#5
